---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
  indentation:
    spaces: 2
    indent-sequences: consistent
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0

ignore: |
  .venv/
  .git/
  node_modules/
  .github/
